os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode9.4
branches:
  only:
    - master
before_install:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - .travis/update-submodule.sh
script:
  - .travis/ci.sh
notifications:
  email:
    recipients:
    - josephblau@gmail.com
deploy:
  provider: heroku
  strategy: git
  app: gitignoreio-stage-swift
  on: master
  api_key:
    secure: In+pMxDoWCe5h2oCi20pCpLGLdiqvP1SuWqTkFm1G1LPtZ7LIcIbxlCgiWGlWqaPnwC5n0VkpOEkOSnFZz2E7ffKQuzonvEBUPl5EFLzfJxeHUDWaaMGWfadx2kR21cx/wTyEZseSqeBm77wbKJKU7D6RqRbCS+MxaavQhaJnKk=
env:
  global:
    - secure: ZubW/TIAZCjYPJYI1mwUtWhY9iAabIQzyeexKGEbcbUuYhdCzZ2Dj7mIjPyOQ0KPwQm3nwWPRXq8V7YnGJMU3ytofu/PTb0gYDGPguVpLj0k7hN3xlxuODQeP2BtiS4uzuXspMfOb14kEkszFqU0qlF/eKnKBtqvva//Iwi2L3I=
