os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode9.4
branches:
  only:
  - master
before_install:
  - rvm install 2.2.2
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - .travis/update-submodule.sh
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - gem install slather
  - .travis/ci.sh
after_script:
  - slather coverage --cobertura-xml --source-directory ./Sources/ --output-directory ./ --scheme AppTests ./GitignoreIO.xcodeproj                                                                ✓  10657
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  email:
    recipients:
    - josephblau@gmail.com
deploy:
  provider: heroku
  strategy: git
  app: gitignoreio-stage-swift
  on: master
  api_key:
    secure: In+pMxDoWCe5h2oCi20pCpLGLdiqvP1SuWqTkFm1G1LPtZ7LIcIbxlCgiWGlWqaPnwC5n0VkpOEkOSnFZz2E7ffKQuzonvEBUPl5EFLzfJxeHUDWaaMGWfadx2kR21cx/wTyEZseSqeBm77wbKJKU7D6RqRbCS+MxaavQhaJnKk=
env:
  global:
    - secure: ZubW/TIAZCjYPJYI1mwUtWhY9iAabIQzyeexKGEbcbUuYhdCzZ2Dj7mIjPyOQ0KPwQm3nwWPRXq8V7YnGJMU3ytofu/PTb0gYDGPguVpLj0k7hN3xlxuODQeP2BtiS4uzuXspMfOb14kEkszFqU0qlF/eKnKBtqvva//Iwi2L3I=
    