language: generic
sudo: required
dist: trusty
osx_image: xcode8
install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/02090c7ede5a637b76e6df1710e83cd0bbe7dcdf/swiftenv-install.sh)"
  - ./install_swiftlint.sh
script:
  - swiftlint
  - swift build
  - swift build -c release
after_success:
  - bash <(curl -s https://codecov.io/bash)
