os:
- linux
- osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8.2
branches:
  only:
  - master
script:
- eval "$(curl -sL https://swift.vapor.sh/ci)"
- eval "$(curl -sL https://swift.vapor.sh/codecov)"
notifications:
  email:
    recipients:
      - josephblau@gmail.com
deploy:
  provider: heroku
  strategy: git
  app: gitignoreio-stage-swift
  on: master
  api_key:
    secure: In+pMxDoWCe5h2oCi20pCpLGLdiqvP1SuWqTkFm1G1LPtZ7LIcIbxlCgiWGlWqaPnwC5n0VkpOEkOSnFZz2E7ffKQuzonvEBUPl5EFLzfJxeHUDWaaMGWfadx2kR21cx/wTyEZseSqeBm77wbKJKU7D6RqRbCS+MxaavQhaJnKk=
